### ISSUE TITLE
Uploading to SoundCloud

### ISSUE THREAD

**Issue by rajikaimal** [monbro/soundcloud-nodejs-api-wrapper#1]
How can we upload audio files to SoundCloud, there's no endpoint in SoundCloud documentation for uploading audio files.

**Comment by monbro** [comment]
I never tried this in nodeJS but have a look here https://developers.soundcloud.com/docs/api/guide#uploading 

`To upload a sound, send a POST request to the /tracks endpoint. This is done with one of our SDKs using the post method and passing information about the track being uploaded.`

Potentially look into the code of the official SDK for this method call (SC.upload).

**Comment by rajikaimal** [comment]
Got it ! thanks for the reply :+1:
