### ISSUE TITLE
Invalid Grant: unable to authenticate

### ISSUE THREAD

**Issue by Whitevinyl** [monbro/soundcloud-nodejs-api-wrapper#2]
Hi, I'm trying to use Example C to authenticate with the User Credentials Flow.
If I paste it as-is (with my credentials added) I get an error saying:

```
var access_token = arguments[3].access_token;
                                   ^
TypeError: Cannot read property 'access_token' of undefined
```

If I comment out everything in the function except console logging it logs this:

```
Full API auth response was:
{ '0': { statusCode: 401, data: '{"error":"invalid_grant"}' } }
```

Any ideas why? If I intentionally typo the client details I get "invalid_client" so those seem to get picked up fine. Would hugely appreciate any help! Thanks!

**Comment by timpulver** [comment]
Just had the same `401` problem. In my case I used an expired access token. Getting a new one solved the problem.
Maybe this helps: [github.com/timpulver/soundcloud-unfollower-helper/blob/master/get_access_token.js](https://github.com/timpulver/soundcloud-unfollower-helper/blob/master/get_access_token.js)

**Comment by timpulver** [comment]
Another idea – did you use your user name instead of the email-address?

**Comment by Whitevinyl** [comment]
Ah damn - it was me!
I'd checked over the credentials so many times, but I'd made a new SoundCloud account especially to test this - turns out I'd misspelled my password on the account itself, I just reset it and it's connecting up fine now. Thanks!

**Comment by monbro** [comment]
Haha had the same, changed my password and was confused why the codebase was not working anymore -.-
